"""The order to verdict the edges in, printed from edges.json rather than pasted.

    python3 dep_worklist.py            # print
    python3 dep_worklist.py --write    # print and write dependency_worklist.md

WHY THIS IS A SCRIPT. Every edge in edges.json carries `verdict: null` and the
verdict is the reader's field. The list of what is still unverdicted is therefore
a number that changes every time one is filled in, and a pasted list would be
wrong by the following morning. This regenerates.

THE ORDER IS THE RULING'S. Edges matched to an admitted register row come first
and are grouped by row, because those are the ones a verdict moves something: a
row gains a supplier, or it does not. Then the edges that name a site this
register does not hold, grouped by site, because those are the census's question.
Then everything else, grouped by node.

WHAT EACH LINE CARRIES is what the ruling asked for and nothing else: firmness,
speaker, date, source, verdict. `firmness` is first because rung 6 of the
confirmation ladder passes on `contract` and on nothing else, so a reader
verdicting for the ladder can stop at the first column.
"""
from __future__ import annotations

import collections
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent


def load() -> tuple[list[dict], dict[str, dict]]:
    edges = json.loads((HERE / "edges.json").read_text())["edges"]
    nodes = {n["id"]: n for n in json.loads((HERE / "nodes.json").read_text())["nodes"]}
    return edges, nodes


def line(e: dict, nodes: dict) -> list[str]:
    q = e["quantity"]
    out = [f"- **{e['id']}**  `{e['firmness']}`  {e['date']}"
           + (f" ({e['date_precision']})" if e["date_precision"] != "day" else "")
           + f"  speaker: {e['speaker']}  verdict: **null**",
           f"  - {nodes[e['node_id']]['name']} → {e['customer_name_as_stated']}"
           + (f" — {q['value']:,g} {q['unit']}" if q else " — no quantity stated"),
           f"  - source: {e['url']}"]
    if e["captured_at"]:
        out.append(f"  - copy on file captured {e['captured_at']}")
    if e["inherited_by"]:
        out.append(f"  - inherited by {e['inherited_by']['node_id']} "
                   f"from {e['inherited_by']['since']}")
    out.append(f"  - cited for firmness: “{e['firmness_basis']}”")
    return out


def render() -> str:
    edges, nodes = load()
    matched = [e for e in edges if e["project_id"]]
    outside = [e for e in edges if e["outside_perimeter"]]
    done = {e["id"] for e in matched} | {e["id"] for e in outside}
    rest = [e for e in edges if e["id"] not in done]
    L: list[str] = [
        "# Verdict worklist — brief 9",
        "",
        "Regenerated by `python3 sources/dep_worklist.py --write`. Every edge below "
        "carries `verdict: null`; filling one in is an edit to `sources/dep_readings.py` "
        "and a rebuild, not an edit to this file.",
        "",
        f"**{len(matched)} matched to a register row · {len(outside)} at a site this "
        f"register does not hold · {len(rest)} neither · {len(edges)} edges in total.**",
        "",
        "Firmness counts across the whole file: "
        + ", ".join(f"{k} {v}" for k, v in
                    sorted(collections.Counter(e["firmness"] for e in edges).items()))
        + ". Rung 6 of the confirmation ladder passes on `contract` only.",
        "",
        "---",
        "",
        "## 1. Matched to a register row — work these first",
        "",
        "A verdict here attaches a supplier to an admitted row, or refuses to. "
        "`match_basis` says what the link rests on: `site only` is a place name with no "
        "company agreement and is the weakest of the three.",
        "",
    ]
    by_row = collections.defaultdict(list)
    for e in matched:
        by_row[e["project_id"]].append(e)
    for pid in sorted(by_row):
        group = sorted(by_row[pid], key=lambda e: e["date"])
        bases = sorted({e["match_basis"] for e in group})
        L += [f"### `{pid}` — {len(group)} edge(s), matched on {', '.join(bases)}", ""]
        for e in group:
            L += line(e, nodes)
        L.append("")

    L += ["---", "",
          "## 2. A named site this register does not hold",
          "",
          "`outside_perimeter: true`. These count toward the supplier's totals and "
          "toward no project. Grouped by the site as the supplier stated it.",
          ""]
    by_site = collections.defaultdict(list)
    for e in outside:
        by_site[e["site_as_stated"]].append(e)
    for site in sorted(by_site):
        group = sorted(by_site[site], key=lambda e: e["date"])
        sectors = sorted({e["sector"] for e in group if e["sector"]})
        L += [f"### {site}" + (f" — {', '.join(sectors)}" if sectors else ""), ""]
        for e in group:
            L += line(e, nodes)
        L.append("")

    L += ["---", "",
          "## 3. Everything else",
          "",
          "A customer nobody named, or a company named without a site. Grouped by node.",
          ""]
    by_node = collections.defaultdict(list)
    for e in rest:
        by_node[e["node_id"]].append(e)
    for nid in sorted(by_node):
        group = sorted(by_node[nid], key=lambda e: e["date"])
        L += [f"### {nodes[nid]['name']} — {len(group)} edge(s)", ""]
        for e in group:
            L += line(e, nodes)
        L.append("")
    return "\n".join(L) + "\n"


if __name__ == "__main__":
    text = render()
    if "--write" in sys.argv[1:]:
        (HERE / "dependency_worklist.md").write_text(text)
        print(f"dependency_worklist.md — {text.count(chr(10))} lines")
    else:
        print(text)
